### ISSUE TITLE
Error executing process > 'installVEPcache (installVEPcache)'

### ISSUE THREAD

**Issue by beijish** [icbi-lab/nextNEOpi#7] opened 2022-07-02 21:33 UTC
Good evening,

thank you very much for sharing this tool, very useful.
However, I am stuck. I am trying to run it on an HPC (unix, LMOD) system, with these settings:
$PBS_O_WORKDIR/nextflow run $PBS_O_WORKDIR/nextNEOpi.nf 
--batchFile  $PBS_O_WORKDIR/batchFile_FASTQ.csv  
-profile singularity,cluster  
-config $PBS_O_WORKDIR/conf/params.config  
--accept_license  
--outputDir $PBS_O_WORKDIR/nextNEOpi_results  
--tmpDir $PBS_O_WORKDIR/tmp  
--HLAHD_DIR  $PBS_O_WORKDIR/hlahd.1.5.0  
-resume
 
It starts, and after few hours it terminates with this:

Error executing process > 'installVEPcache (installVEPcache)'

Caused by:
  Process `installVEPcache (installVEPcache)` terminated with an error exit status (30)

Command executed:

  mkdir -p /xxx/resources/databases/vep_cache
  vep_install \
      -a cf \
      -s homo_sapiens \
      -y GRCh38 \
      -c /xxx/resources/databases/vep_cache \
      --CACHE_VERSION 105 \
      --CONVERT 2> vep_errors.txt && \
  echo "OK" > .homo_sapiens_GRCh38_105_cache_ok.chck && \
  cp -f  .homo_sapiens_GRCh38_105_cache_ok.chck /mnt/panfs1/scratch/wsspaces/svalpione-Kim2018-0/WES/resources/databases/vep_cache/.homo_sapiens_GRCh38_105_cache_ok.chck

Command exit status:
  30

Command output:
  curl failed (000), trying to fetch using LWP::Simple
  LWP::Simple failed (500), trying to fetch using HTTP::Tiny

Command wrapper:
  curl failed (000), trying to fetch using LWP::Simple
  LWP::Simple failed (500), trying to fetch using HTTP::Tiny

Work dir:
  /xxx/work/cc/81435e84c23743ca08bca184d1ce9c

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run` 

I the server is connected to Internet, I have tried to install VEP and populate vep_cache prior to launching the job but it makes no difference.
 Any suggestions, please?

Thank you a lot

S

**Comment by riederd** [comment] 2022-07-04 06:45
Hi, thanks for your interest in nextNEOpi.

To me this looks like a temporary connection/server issue. Seen that you installed the vep_cache manually, you may try the following:

```
$ echo OK > /mnt/panfs1/scratch/wsspaces/svalpione-Kim2018-0/WES/resources/databases/vep_cache/.homo_sapiens_GRCh38_105_cache_ok.chck
```

And then resume the pipeline.
All assuming that you successfully installed the vep_cache in `/mnt/panfs1/scratch/wsspaces/svalpione-Kim2018-0/WES/resources/databases/vep_cache/`

**Comment by riederd** [comment] 2022-07-18 07:40
No feedback, assuming that the issue is fixed. Closing it for now, feel free to reopen.

**Closed by riederd** 2022-07-18 07:40 UTC

**Comment by beijish** [comment] 2022-07-20 10:16
Hi, it worked installing manually. There is a problem with certificates that prevents the connections called by vep_install. I have been able to bypass most of these skipping the certificate check for most curl/wget commands in the nextNEOpi pipeline. You might want to look into this for the next releases?
Thanks

SV

**Comment by beijish** [comment] 2022-08-02 11:15
Thank you, it turned out there was a problem with certificates with our nodes. Help much appreciated.

SV

**Comment by riederd** [comment] 2022-08-02 13:00
Glad you found the problem
